### ISSUE TITLE
Problem filtering instances

### ISSUE THREAD

**Issue by ghost** [cgearhart/students-filters#9]
Hi,

I have followed the instructions on how to install your ICA plugin in WEKA;however, I didn't have any luck. I'm using the pima indian diabetes dataset. If I try to run the filter thorugh WEKA GUI I get the following error "Problem filtering instances".

Any help or advice is greatly appreciated. Thanks in advance for your help and time

**Comment by SunYuzhuo** [comment]
I got the same error. Would be appreciated for help :)

**Comment by daphnechen** [comment]
bump

**Comment by cgearhart** [comment]
Sorry for the slow response—I haven't paid much attention here for a few years.

Version 1 of the filter contained a bug when the input data included a class attribute. The new version in commit c353897 correctly handles class attributes by passing them through the filter unchanged.
